services:
  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./backend:/var/www/html
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - backend_network
    depends_on:
      - php
    container_name: clarify_nginx

  mysql:
    image: mysql:8.0.34
    environment:
      MYSQL_ROOT_PASSWORD: claryfi
      MYSQL_DATABASE: claryfi
      MYSQL_USER: claryfi
      MYSQL_PASSWORD: claryfi
    volumes:
      - database_data:/var/lib/mysql:rw
    ports:
      - "3306:3306"
    networks:
      - backend_network
    restart: unless-stopped
    container_name: clarify_mysql

  php:
    build:
      context: ./docker/php
    environment:
      DATABASE_URL: "mysql://claryfi:claryfi@mysql:3306/claryfi?serverVersion=8.0.34&charset=utf8mb4"
      APP_ENV: dev
      MYSQL_DATABASE: claryfi
      MYSQL_USER: claryfi
      MYSQL_PASSWORD: claryfi
    volumes:
      - ./backend:/var/www/html
    networks:
      - backend_network
    restart: unless-stopped
    container_name: clarify_php
    depends_on:
      - mysql

  node:
    build:
      context: ./frontend
      dockerfile: ../docker/node/Dockerfile
    volumes:
      - ./frontend:/app:cached
      - node_modules:/app/node_modules
    ports:
      #- "3000:3000"
      - "5173:5173"
    container_name: clarify_node
    user: "node"
    environment:
      - NODE_ENV=development

volumes:
  database_data:
  node_modules:

networks:
  backend_network:
    driver: bridge